site_name: BAM Masterdata
site_description: Documentation page for the BAM Masterdata.
site_author: BAM Data Store
repo_url: https://github.com/BAMresearch/bam-masterdata
nav:
  - Home: index.md
  - Tutorial: tutorials/tutorial.md
  - How-to guides:
    - Overview: howtos/overview.md
  - Explanations:
    - Data Store: explanations/data-store.md
    - OpenBIS : explanations/openbis.md
    - pyBIS : explanations/pybis.md
  - References:
    - Collection: references/collection.md
    - Controlled Vocabulary: references/controlled-vocabulary.md
    - Dataset: references/dataset.md
theme:
  name: material
  palette:
    primary: custom
    accent: custom
    # - scheme: default
    # - media: "(prefers-color-scheme: light)"
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to light mode
    # - scheme: slate
    # - media: "(prefers-color-scheme: dark)"
      # toggle:
      #   icon: material/weather-night
      #   name: Switch to dark mode
  logo: assets/bammasterdata_blue_transparent.png
  favicon: assets/bammasterdata_blue_transparent.png
  features:
    - navigation.path
    - navigation.footer
    - navigation.top
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: true  # show inheritance from classes
            show_source: true  # show source code
            show_if_no_docstring: true  # show methods if they don't have docstrings
            show_labels: false  # not showing labels in class attrs
            docstring_section_style: spacy  # different style for input parameters of methods
            members_order: source  # order of definitions according to source code
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js'
  - 'https://unpkg.com/cytoscape@3.19.1/dist/cytoscape.min.js'
  - 'https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js'